Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    q_input_1:
      Precision:
        result: fixed<12,11>
      Trace: false
    q_separable_conv2d:
      Precision:
        bias: fixed<12,11>
        depthwise: fixed<12,11>
        pointwise: fixed<12,11>
        result: fixed<16,6>
      Trace: false
    q_separable_conv2d_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_prj/keras_model.h5'
OutputDir: hls4ml_prj
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 5AAf5f75
Version: 1.0.0
