-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    q_input_1_V : IN STD_LOGIC_VECTOR (359 downto 0);
    layer4_out_0_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_1_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_2_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_3_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_4_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_5_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_6_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_7_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_8_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_9_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_10_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_11_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_12_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_13_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_14_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_15_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_16_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_17_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_18_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_19_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_20_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_21_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_22_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_23_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_24_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_25_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_26_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_27_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_28_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_29_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_30_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_31_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_32_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_33_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_34_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_35_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_36_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_37_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_38_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_39_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_40_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_41_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_42_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_43_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_44_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_45_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_46_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_47_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_48_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_49_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_50_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_51_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_52_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_53_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_54_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_55_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_56_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_57_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_58_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    layer4_out_59_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    q_input_1_V_ap_vld : IN STD_LOGIC;
    layer4_out_0_V_ap_vld : OUT STD_LOGIC;
    layer4_out_1_V_ap_vld : OUT STD_LOGIC;
    layer4_out_2_V_ap_vld : OUT STD_LOGIC;
    layer4_out_3_V_ap_vld : OUT STD_LOGIC;
    layer4_out_4_V_ap_vld : OUT STD_LOGIC;
    layer4_out_5_V_ap_vld : OUT STD_LOGIC;
    layer4_out_6_V_ap_vld : OUT STD_LOGIC;
    layer4_out_7_V_ap_vld : OUT STD_LOGIC;
    layer4_out_8_V_ap_vld : OUT STD_LOGIC;
    layer4_out_9_V_ap_vld : OUT STD_LOGIC;
    layer4_out_10_V_ap_vld : OUT STD_LOGIC;
    layer4_out_11_V_ap_vld : OUT STD_LOGIC;
    layer4_out_12_V_ap_vld : OUT STD_LOGIC;
    layer4_out_13_V_ap_vld : OUT STD_LOGIC;
    layer4_out_14_V_ap_vld : OUT STD_LOGIC;
    layer4_out_15_V_ap_vld : OUT STD_LOGIC;
    layer4_out_16_V_ap_vld : OUT STD_LOGIC;
    layer4_out_17_V_ap_vld : OUT STD_LOGIC;
    layer4_out_18_V_ap_vld : OUT STD_LOGIC;
    layer4_out_19_V_ap_vld : OUT STD_LOGIC;
    layer4_out_20_V_ap_vld : OUT STD_LOGIC;
    layer4_out_21_V_ap_vld : OUT STD_LOGIC;
    layer4_out_22_V_ap_vld : OUT STD_LOGIC;
    layer4_out_23_V_ap_vld : OUT STD_LOGIC;
    layer4_out_24_V_ap_vld : OUT STD_LOGIC;
    layer4_out_25_V_ap_vld : OUT STD_LOGIC;
    layer4_out_26_V_ap_vld : OUT STD_LOGIC;
    layer4_out_27_V_ap_vld : OUT STD_LOGIC;
    layer4_out_28_V_ap_vld : OUT STD_LOGIC;
    layer4_out_29_V_ap_vld : OUT STD_LOGIC;
    layer4_out_30_V_ap_vld : OUT STD_LOGIC;
    layer4_out_31_V_ap_vld : OUT STD_LOGIC;
    layer4_out_32_V_ap_vld : OUT STD_LOGIC;
    layer4_out_33_V_ap_vld : OUT STD_LOGIC;
    layer4_out_34_V_ap_vld : OUT STD_LOGIC;
    layer4_out_35_V_ap_vld : OUT STD_LOGIC;
    layer4_out_36_V_ap_vld : OUT STD_LOGIC;
    layer4_out_37_V_ap_vld : OUT STD_LOGIC;
    layer4_out_38_V_ap_vld : OUT STD_LOGIC;
    layer4_out_39_V_ap_vld : OUT STD_LOGIC;
    layer4_out_40_V_ap_vld : OUT STD_LOGIC;
    layer4_out_41_V_ap_vld : OUT STD_LOGIC;
    layer4_out_42_V_ap_vld : OUT STD_LOGIC;
    layer4_out_43_V_ap_vld : OUT STD_LOGIC;
    layer4_out_44_V_ap_vld : OUT STD_LOGIC;
    layer4_out_45_V_ap_vld : OUT STD_LOGIC;
    layer4_out_46_V_ap_vld : OUT STD_LOGIC;
    layer4_out_47_V_ap_vld : OUT STD_LOGIC;
    layer4_out_48_V_ap_vld : OUT STD_LOGIC;
    layer4_out_49_V_ap_vld : OUT STD_LOGIC;
    layer4_out_50_V_ap_vld : OUT STD_LOGIC;
    layer4_out_51_V_ap_vld : OUT STD_LOGIC;
    layer4_out_52_V_ap_vld : OUT STD_LOGIC;
    layer4_out_53_V_ap_vld : OUT STD_LOGIC;
    layer4_out_54_V_ap_vld : OUT STD_LOGIC;
    layer4_out_55_V_ap_vld : OUT STD_LOGIC;
    layer4_out_56_V_ap_vld : OUT STD_LOGIC;
    layer4_out_57_V_ap_vld : OUT STD_LOGIC;
    layer4_out_58_V_ap_vld : OUT STD_LOGIC;
    layer4_out_59_V_ap_vld : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.678719,HLS_SYN_LAT=7,HLS_SYN_TPT=8,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=427,HLS_SYN_LUT=10095,HLS_VERSION=2019_1}";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_start : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_done : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_continue : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_idle : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_ready : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V_ap_vld : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V : STD_LOGIC_VECTOR (15 downto 0);
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V_ap_vld : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_start_full_n : STD_LOGIC;
    signal pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_start_write : STD_LOGIC;

    component pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V : IN STD_LOGIC_VECTOR (359 downto 0);
        data_V_ap_vld : IN STD_LOGIC;
        res_0_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_0_V_ap_vld : OUT STD_LOGIC;
        res_1_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_1_V_ap_vld : OUT STD_LOGIC;
        res_2_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_2_V_ap_vld : OUT STD_LOGIC;
        res_3_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_3_V_ap_vld : OUT STD_LOGIC;
        res_4_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_4_V_ap_vld : OUT STD_LOGIC;
        res_5_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_5_V_ap_vld : OUT STD_LOGIC;
        res_6_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_6_V_ap_vld : OUT STD_LOGIC;
        res_7_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_7_V_ap_vld : OUT STD_LOGIC;
        res_8_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_8_V_ap_vld : OUT STD_LOGIC;
        res_9_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_9_V_ap_vld : OUT STD_LOGIC;
        res_10_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_10_V_ap_vld : OUT STD_LOGIC;
        res_11_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_11_V_ap_vld : OUT STD_LOGIC;
        res_12_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_12_V_ap_vld : OUT STD_LOGIC;
        res_13_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_13_V_ap_vld : OUT STD_LOGIC;
        res_14_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_14_V_ap_vld : OUT STD_LOGIC;
        res_15_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_15_V_ap_vld : OUT STD_LOGIC;
        res_16_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_16_V_ap_vld : OUT STD_LOGIC;
        res_17_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_17_V_ap_vld : OUT STD_LOGIC;
        res_18_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_18_V_ap_vld : OUT STD_LOGIC;
        res_19_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_19_V_ap_vld : OUT STD_LOGIC;
        res_20_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_20_V_ap_vld : OUT STD_LOGIC;
        res_21_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_21_V_ap_vld : OUT STD_LOGIC;
        res_22_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_22_V_ap_vld : OUT STD_LOGIC;
        res_23_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_23_V_ap_vld : OUT STD_LOGIC;
        res_24_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_24_V_ap_vld : OUT STD_LOGIC;
        res_25_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_25_V_ap_vld : OUT STD_LOGIC;
        res_26_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_26_V_ap_vld : OUT STD_LOGIC;
        res_27_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_27_V_ap_vld : OUT STD_LOGIC;
        res_28_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_28_V_ap_vld : OUT STD_LOGIC;
        res_29_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_29_V_ap_vld : OUT STD_LOGIC;
        res_30_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_30_V_ap_vld : OUT STD_LOGIC;
        res_31_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_31_V_ap_vld : OUT STD_LOGIC;
        res_32_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_32_V_ap_vld : OUT STD_LOGIC;
        res_33_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_33_V_ap_vld : OUT STD_LOGIC;
        res_34_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_34_V_ap_vld : OUT STD_LOGIC;
        res_35_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_35_V_ap_vld : OUT STD_LOGIC;
        res_36_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_36_V_ap_vld : OUT STD_LOGIC;
        res_37_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_37_V_ap_vld : OUT STD_LOGIC;
        res_38_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_38_V_ap_vld : OUT STD_LOGIC;
        res_39_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_39_V_ap_vld : OUT STD_LOGIC;
        res_40_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_40_V_ap_vld : OUT STD_LOGIC;
        res_41_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_41_V_ap_vld : OUT STD_LOGIC;
        res_42_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_42_V_ap_vld : OUT STD_LOGIC;
        res_43_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_43_V_ap_vld : OUT STD_LOGIC;
        res_44_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_44_V_ap_vld : OUT STD_LOGIC;
        res_45_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_45_V_ap_vld : OUT STD_LOGIC;
        res_46_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_46_V_ap_vld : OUT STD_LOGIC;
        res_47_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_47_V_ap_vld : OUT STD_LOGIC;
        res_48_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_48_V_ap_vld : OUT STD_LOGIC;
        res_49_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_49_V_ap_vld : OUT STD_LOGIC;
        res_50_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_50_V_ap_vld : OUT STD_LOGIC;
        res_51_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_51_V_ap_vld : OUT STD_LOGIC;
        res_52_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_52_V_ap_vld : OUT STD_LOGIC;
        res_53_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_53_V_ap_vld : OUT STD_LOGIC;
        res_54_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_54_V_ap_vld : OUT STD_LOGIC;
        res_55_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_55_V_ap_vld : OUT STD_LOGIC;
        res_56_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_56_V_ap_vld : OUT STD_LOGIC;
        res_57_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_57_V_ap_vld : OUT STD_LOGIC;
        res_58_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_58_V_ap_vld : OUT STD_LOGIC;
        res_59_V : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_59_V_ap_vld : OUT STD_LOGIC );
    end component;



begin
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0 : component pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_start,
        ap_done => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_done,
        ap_continue => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_continue,
        ap_idle => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_idle,
        ap_ready => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_ready,
        data_V => q_input_1_V,
        data_V_ap_vld => q_input_1_V_ap_vld,
        res_0_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V,
        res_0_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V_ap_vld,
        res_1_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V,
        res_1_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V_ap_vld,
        res_2_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V,
        res_2_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V_ap_vld,
        res_3_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V,
        res_3_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V_ap_vld,
        res_4_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V,
        res_4_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V_ap_vld,
        res_5_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V,
        res_5_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V_ap_vld,
        res_6_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V,
        res_6_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V_ap_vld,
        res_7_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V,
        res_7_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V_ap_vld,
        res_8_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V,
        res_8_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V_ap_vld,
        res_9_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V,
        res_9_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V_ap_vld,
        res_10_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V,
        res_10_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V_ap_vld,
        res_11_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V,
        res_11_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V_ap_vld,
        res_12_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V,
        res_12_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V_ap_vld,
        res_13_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V,
        res_13_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V_ap_vld,
        res_14_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V,
        res_14_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V_ap_vld,
        res_15_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V,
        res_15_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V_ap_vld,
        res_16_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V,
        res_16_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V_ap_vld,
        res_17_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V,
        res_17_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V_ap_vld,
        res_18_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V,
        res_18_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V_ap_vld,
        res_19_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V,
        res_19_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V_ap_vld,
        res_20_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V,
        res_20_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V_ap_vld,
        res_21_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V,
        res_21_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V_ap_vld,
        res_22_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V,
        res_22_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V_ap_vld,
        res_23_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V,
        res_23_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V_ap_vld,
        res_24_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V,
        res_24_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V_ap_vld,
        res_25_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V,
        res_25_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V_ap_vld,
        res_26_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V,
        res_26_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V_ap_vld,
        res_27_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V,
        res_27_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V_ap_vld,
        res_28_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V,
        res_28_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V_ap_vld,
        res_29_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V,
        res_29_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V_ap_vld,
        res_30_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V,
        res_30_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V_ap_vld,
        res_31_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V,
        res_31_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V_ap_vld,
        res_32_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V,
        res_32_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V_ap_vld,
        res_33_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V,
        res_33_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V_ap_vld,
        res_34_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V,
        res_34_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V_ap_vld,
        res_35_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V,
        res_35_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V_ap_vld,
        res_36_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V,
        res_36_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V_ap_vld,
        res_37_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V,
        res_37_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V_ap_vld,
        res_38_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V,
        res_38_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V_ap_vld,
        res_39_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V,
        res_39_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V_ap_vld,
        res_40_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V,
        res_40_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V_ap_vld,
        res_41_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V,
        res_41_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V_ap_vld,
        res_42_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V,
        res_42_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V_ap_vld,
        res_43_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V,
        res_43_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V_ap_vld,
        res_44_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V,
        res_44_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V_ap_vld,
        res_45_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V,
        res_45_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V_ap_vld,
        res_46_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V,
        res_46_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V_ap_vld,
        res_47_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V,
        res_47_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V_ap_vld,
        res_48_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V,
        res_48_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V_ap_vld,
        res_49_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V,
        res_49_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V_ap_vld,
        res_50_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V,
        res_50_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V_ap_vld,
        res_51_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V,
        res_51_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V_ap_vld,
        res_52_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V,
        res_52_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V_ap_vld,
        res_53_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V,
        res_53_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V_ap_vld,
        res_54_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V,
        res_54_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V_ap_vld,
        res_55_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V,
        res_55_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V_ap_vld,
        res_56_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V,
        res_56_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V_ap_vld,
        res_57_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V,
        res_57_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V_ap_vld,
        res_58_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V,
        res_58_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V_ap_vld,
        res_59_V => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V,
        res_59_V_ap_vld => pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V_ap_vld);




    ap_done <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_done;
    ap_idle <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_idle;
    ap_ready <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_ready;
    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_done;
    ap_sync_ready <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_ready;
    layer4_out_0_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V;
    layer4_out_0_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_0_V_ap_vld;
    layer4_out_10_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V;
    layer4_out_10_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_10_V_ap_vld;
    layer4_out_11_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V;
    layer4_out_11_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_11_V_ap_vld;
    layer4_out_12_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V;
    layer4_out_12_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_12_V_ap_vld;
    layer4_out_13_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V;
    layer4_out_13_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_13_V_ap_vld;
    layer4_out_14_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V;
    layer4_out_14_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_14_V_ap_vld;
    layer4_out_15_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V;
    layer4_out_15_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_15_V_ap_vld;
    layer4_out_16_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V;
    layer4_out_16_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_16_V_ap_vld;
    layer4_out_17_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V;
    layer4_out_17_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_17_V_ap_vld;
    layer4_out_18_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V;
    layer4_out_18_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_18_V_ap_vld;
    layer4_out_19_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V;
    layer4_out_19_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_19_V_ap_vld;
    layer4_out_1_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V;
    layer4_out_1_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_1_V_ap_vld;
    layer4_out_20_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V;
    layer4_out_20_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_20_V_ap_vld;
    layer4_out_21_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V;
    layer4_out_21_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_21_V_ap_vld;
    layer4_out_22_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V;
    layer4_out_22_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_22_V_ap_vld;
    layer4_out_23_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V;
    layer4_out_23_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_23_V_ap_vld;
    layer4_out_24_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V;
    layer4_out_24_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_24_V_ap_vld;
    layer4_out_25_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V;
    layer4_out_25_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_25_V_ap_vld;
    layer4_out_26_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V;
    layer4_out_26_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_26_V_ap_vld;
    layer4_out_27_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V;
    layer4_out_27_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_27_V_ap_vld;
    layer4_out_28_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V;
    layer4_out_28_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_28_V_ap_vld;
    layer4_out_29_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V;
    layer4_out_29_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_29_V_ap_vld;
    layer4_out_2_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V;
    layer4_out_2_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_2_V_ap_vld;
    layer4_out_30_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V;
    layer4_out_30_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_30_V_ap_vld;
    layer4_out_31_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V;
    layer4_out_31_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_31_V_ap_vld;
    layer4_out_32_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V;
    layer4_out_32_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_32_V_ap_vld;
    layer4_out_33_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V;
    layer4_out_33_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_33_V_ap_vld;
    layer4_out_34_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V;
    layer4_out_34_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_34_V_ap_vld;
    layer4_out_35_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V;
    layer4_out_35_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_35_V_ap_vld;
    layer4_out_36_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V;
    layer4_out_36_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_36_V_ap_vld;
    layer4_out_37_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V;
    layer4_out_37_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_37_V_ap_vld;
    layer4_out_38_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V;
    layer4_out_38_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_38_V_ap_vld;
    layer4_out_39_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V;
    layer4_out_39_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_39_V_ap_vld;
    layer4_out_3_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V;
    layer4_out_3_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_3_V_ap_vld;
    layer4_out_40_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V;
    layer4_out_40_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_40_V_ap_vld;
    layer4_out_41_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V;
    layer4_out_41_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_41_V_ap_vld;
    layer4_out_42_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V;
    layer4_out_42_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_42_V_ap_vld;
    layer4_out_43_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V;
    layer4_out_43_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_43_V_ap_vld;
    layer4_out_44_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V;
    layer4_out_44_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_44_V_ap_vld;
    layer4_out_45_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V;
    layer4_out_45_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_45_V_ap_vld;
    layer4_out_46_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V;
    layer4_out_46_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_46_V_ap_vld;
    layer4_out_47_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V;
    layer4_out_47_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_47_V_ap_vld;
    layer4_out_48_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V;
    layer4_out_48_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_48_V_ap_vld;
    layer4_out_49_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V;
    layer4_out_49_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_49_V_ap_vld;
    layer4_out_4_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V;
    layer4_out_4_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_4_V_ap_vld;
    layer4_out_50_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V;
    layer4_out_50_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_50_V_ap_vld;
    layer4_out_51_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V;
    layer4_out_51_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_51_V_ap_vld;
    layer4_out_52_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V;
    layer4_out_52_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_52_V_ap_vld;
    layer4_out_53_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V;
    layer4_out_53_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_53_V_ap_vld;
    layer4_out_54_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V;
    layer4_out_54_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_54_V_ap_vld;
    layer4_out_55_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V;
    layer4_out_55_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_55_V_ap_vld;
    layer4_out_56_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V;
    layer4_out_56_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_56_V_ap_vld;
    layer4_out_57_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V;
    layer4_out_57_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_57_V_ap_vld;
    layer4_out_58_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V;
    layer4_out_58_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_58_V_ap_vld;
    layer4_out_59_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V;
    layer4_out_59_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_59_V_ap_vld;
    layer4_out_5_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V;
    layer4_out_5_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_5_V_ap_vld;
    layer4_out_6_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V;
    layer4_out_6_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_6_V_ap_vld;
    layer4_out_7_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V;
    layer4_out_7_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_7_V_ap_vld;
    layer4_out_8_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V;
    layer4_out_8_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_8_V_ap_vld;
    layer4_out_9_V <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V;
    layer4_out_9_V_ap_vld <= pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_res_9_V_ap_vld;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_continue <= ap_const_logic_1;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_ap_start <= ap_start;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_start_full_n <= ap_const_logic_1;
    pointwise_conv_2d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config4_U0_start_write <= ap_const_logic_0;
end behav;
